//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSI2_G09
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conferencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conferencia()
        {
            this.Artigo = new HashSet<Artigo>();
            this.Conferencia_Utilizador = new HashSet<Conferencia_Utilizador>();
        }
    
        public int ID { get; set; }
        public string nome { get; set; }
        public int ano { get; set; }
        public string acronimo { get; set; }
        public System.DateTime data_submissao { get; set; }
        public Nullable<System.DateTime> data_revisao { get; set; }
        public int presidente { get; set; }
        public int nota_minima { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artigo> Artigo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conferencia_Utilizador> Conferencia_Utilizador { get; set; }
        public virtual Utilizador Utilizador { get; set; }
    }
}
