//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSI2_G09
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SI2_T1Entities : DbContext
    {
        public SI2_T1Entities()
            : base("name=SI2_T1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artigo> Artigo { get; set; }
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Autor_Artigo> Autor_Artigo { get; set; }
        public virtual DbSet<Conferencia> Conferencia { get; set; }
        public virtual DbSet<Conferencia_Utilizador> Conferencia_Utilizador { get; set; }
        public virtual DbSet<FicheiroPDF> FicheiroPDF { get; set; }
        public virtual DbSet<Instituicao> Instituicao { get; set; }
        public virtual DbSet<Revisor> Revisor { get; set; }
        public virtual DbSet<Revisor_Artigo> Revisor_Artigo { get; set; }
        public virtual DbSet<Utilizador> Utilizador { get; set; }
    
        [DbFunction("SI2_T1Entities", "listCompatibleReviewers")]
        public virtual IQueryable<listCompatibleReviewers_Result> listCompatibleReviewers(Nullable<int> conferenceID, Nullable<int> articleID)
        {
            var conferenceIDParameter = conferenceID.HasValue ?
                new ObjectParameter("conferenceID", conferenceID) :
                new ObjectParameter("conferenceID", typeof(int));
    
            var articleIDParameter = articleID.HasValue ?
                new ObjectParameter("articleID", articleID) :
                new ObjectParameter("articleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<listCompatibleReviewers_Result>("[SI2_T1Entities].[listCompatibleReviewers](@conferenceID, @articleID)", conferenceIDParameter, articleIDParameter);
        }
    
        public virtual int AcceptSubmissionRate(Nullable<int> conferencia_id)
        {
            var conferencia_idParameter = conferencia_id.HasValue ?
                new ObjectParameter("conferencia_id", conferencia_id) :
                new ObjectParameter("conferencia_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AcceptSubmissionRate", conferencia_idParameter);
        }
    
        public virtual int addReviewerToArticle(Nullable<int> conferenceID, Nullable<int> articleID, Nullable<int> reviewerID)
        {
            var conferenceIDParameter = conferenceID.HasValue ?
                new ObjectParameter("conferenceID", conferenceID) :
                new ObjectParameter("conferenceID", typeof(int));
    
            var articleIDParameter = articleID.HasValue ?
                new ObjectParameter("articleID", articleID) :
                new ObjectParameter("articleID", typeof(int));
    
            var reviewerIDParameter = reviewerID.HasValue ?
                new ObjectParameter("reviewerID", reviewerID) :
                new ObjectParameter("reviewerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addReviewerToArticle", conferenceIDParameter, articleIDParameter, reviewerIDParameter);
        }
    
        public virtual int ChangeSubmission(Nullable<System.DateTime> data_corte, Nullable<int> conferencia_id)
        {
            var data_corteParameter = data_corte.HasValue ?
                new ObjectParameter("data_corte", data_corte) :
                new ObjectParameter("data_corte", typeof(System.DateTime));
    
            var conferencia_idParameter = conferencia_id.HasValue ?
                new ObjectParameter("conferencia_id", conferencia_id) :
                new ObjectParameter("conferencia_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeSubmission", data_corteParameter, conferencia_idParameter);
        }
    
        public virtual int CreateUtilizador(string newUser_email, string user_nome)
        {
            var newUser_emailParameter = newUser_email != null ?
                new ObjectParameter("newUser_email", newUser_email) :
                new ObjectParameter("newUser_email", typeof(string));
    
            var user_nomeParameter = user_nome != null ?
                new ObjectParameter("user_nome", user_nome) :
                new ObjectParameter("user_nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateUtilizador", newUser_emailParameter, user_nomeParameter);
        }
    
        public virtual int DeleteUtilizador(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUtilizador", user_idParameter);
        }
    
        public virtual int isDateLowerThanCurrentDate(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("isDateLowerThanCurrentDate", dateParameter);
        }
    
        public virtual int isNewDateLowerThanOldDate(Nullable<System.DateTime> new_date, Nullable<System.DateTime> old_date)
        {
            var new_dateParameter = new_date.HasValue ?
                new ObjectParameter("new_date", new_date) :
                new ObjectParameter("new_date", typeof(System.DateTime));
    
            var old_dateParameter = old_date.HasValue ?
                new ObjectParameter("old_date", old_date) :
                new ObjectParameter("old_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("isNewDateLowerThanOldDate", new_dateParameter, old_dateParameter);
        }
    
        public virtual int RegistoRevisao(Nullable<int> user_id, Nullable<int> artigo_id, Nullable<int> conferencia_id, Nullable<int> nota, string texto)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var artigo_idParameter = artigo_id.HasValue ?
                new ObjectParameter("artigo_id", artigo_id) :
                new ObjectParameter("artigo_id", typeof(int));
    
            var conferencia_idParameter = conferencia_id.HasValue ?
                new ObjectParameter("conferencia_id", conferencia_id) :
                new ObjectParameter("conferencia_id", typeof(int));
    
            var notaParameter = nota.HasValue ?
                new ObjectParameter("nota", nota) :
                new ObjectParameter("nota", typeof(int));
    
            var textoParameter = texto != null ?
                new ObjectParameter("texto", texto) :
                new ObjectParameter("texto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistoRevisao", user_idParameter, artigo_idParameter, conferencia_idParameter, notaParameter, textoParameter);
        }
    
        public virtual int revisedArticle(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("revisedArticle", user_idParameter);
        }
    
        public virtual int UpdateAcronimo(Nullable<int> conferenceID, string newAcronimo)
        {
            var conferenceIDParameter = conferenceID.HasValue ?
                new ObjectParameter("conferenceID", conferenceID) :
                new ObjectParameter("conferenceID", typeof(int));
    
            var newAcronimoParameter = newAcronimo != null ?
                new ObjectParameter("newAcronimo", newAcronimo) :
                new ObjectParameter("newAcronimo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAcronimo", conferenceIDParameter, newAcronimoParameter);
        }
    
        public virtual int UpdateAllInfoUtilizador(Nullable<int> user_id, string newUser_email, string user_nome)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var newUser_emailParameter = newUser_email != null ?
                new ObjectParameter("newUser_email", newUser_email) :
                new ObjectParameter("newUser_email", typeof(string));
    
            var user_nomeParameter = user_nome != null ?
                new ObjectParameter("user_nome", user_nome) :
                new ObjectParameter("user_nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAllInfoUtilizador", user_idParameter, newUser_emailParameter, user_nomeParameter);
        }
    
        public virtual int UpdateDataRevisao(Nullable<int> conferenceID, Nullable<System.DateTime> date)
        {
            var conferenceIDParameter = conferenceID.HasValue ?
                new ObjectParameter("conferenceID", conferenceID) :
                new ObjectParameter("conferenceID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDataRevisao", conferenceIDParameter, dateParameter);
        }
    
        public virtual int UpdateDataSubmissao(Nullable<int> conferenceID, Nullable<System.DateTime> date)
        {
            var conferenceIDParameter = conferenceID.HasValue ?
                new ObjectParameter("conferenceID", conferenceID) :
                new ObjectParameter("conferenceID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDataSubmissao", conferenceIDParameter, dateParameter);
        }
    
        public virtual int UpdateEmailUtilizador(Nullable<int> user_id, string newUser_email)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var newUser_emailParameter = newUser_email != null ?
                new ObjectParameter("newUser_email", newUser_email) :
                new ObjectParameter("newUser_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateEmailUtilizador", user_idParameter, newUser_emailParameter);
        }
    
        public virtual int UpdateNome(Nullable<int> conferenceID, string newName)
        {
            var conferenceIDParameter = conferenceID.HasValue ?
                new ObjectParameter("conferenceID", conferenceID) :
                new ObjectParameter("conferenceID", typeof(int));
    
            var newNameParameter = newName != null ?
                new ObjectParameter("newName", newName) :
                new ObjectParameter("newName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateNome", conferenceIDParameter, newNameParameter);
        }
    
        public virtual int UpdateNomeUtilizador(Nullable<int> user_id, string user_nome)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var user_nomeParameter = user_nome != null ?
                new ObjectParameter("user_nome", user_nome) :
                new ObjectParameter("user_nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateNomeUtilizador", user_idParameter, user_nomeParameter);
        }
    
        public virtual int UpdateNotaConferencia(Nullable<int> conferenceID, Nullable<int> nota)
        {
            var conferenceIDParameter = conferenceID.HasValue ?
                new ObjectParameter("conferenceID", conferenceID) :
                new ObjectParameter("conferenceID", typeof(int));
    
            var notaParameter = nota.HasValue ?
                new ObjectParameter("nota", nota) :
                new ObjectParameter("nota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateNotaConferencia", conferenceIDParameter, notaParameter);
        }
    
        public virtual int UpdatePresidente(Nullable<int> conferenceID, Nullable<int> newPresidentID)
        {
            var conferenceIDParameter = conferenceID.HasValue ?
                new ObjectParameter("conferenceID", conferenceID) :
                new ObjectParameter("conferenceID", typeof(int));
    
            var newPresidentIDParameter = newPresidentID.HasValue ?
                new ObjectParameter("newPresidentID", newPresidentID) :
                new ObjectParameter("newPresidentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePresidente", conferenceIDParameter, newPresidentIDParameter);
        }
    
        public virtual int UpdateUtilizador(string user_mail, string newUser_email, string user_nome)
        {
            var user_mailParameter = user_mail != null ?
                new ObjectParameter("user_mail", user_mail) :
                new ObjectParameter("user_mail", typeof(string));
    
            var newUser_emailParameter = newUser_email != null ?
                new ObjectParameter("newUser_email", newUser_email) :
                new ObjectParameter("newUser_email", typeof(string));
    
            var user_nomeParameter = user_nome != null ?
                new ObjectParameter("user_nome", user_nome) :
                new ObjectParameter("user_nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUtilizador", user_mailParameter, newUser_emailParameter, user_nomeParameter);
        }
    
        public virtual int UtilizadorToAutor(string user_mail)
        {
            var user_mailParameter = user_mail != null ?
                new ObjectParameter("user_mail", user_mail) :
                new ObjectParameter("user_mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UtilizadorToAutor", user_mailParameter);
        }
    
        public virtual int UtilizadorToRevisor(string user_mail)
        {
            var user_mailParameter = user_mail != null ?
                new ObjectParameter("user_mail", user_mail) :
                new ObjectParameter("user_mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UtilizadorToRevisor", user_mailParameter);
        }
    
        public virtual int wroteArticle(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("wroteArticle", user_idParameter);
        }
    }
}
